import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/**
 * 확장 호스트(Node)에서 도는 진입점.
 * VS Code가 넘겨주는 markdown-it 인스턴스에 pug-frame 코드펜스 규칙을 추가한다.
 * `vscode`는 런타임에 호스트가 제공하므로 external.
 */
const extensionBuild = {
	banner: { js: banner },
	entryPoints: ['src/extension.ts'],
	bundle: true,
	platform: 'node',
	format: 'cjs',
	target: 'node18',
	external: ['vscode', ...builtinModules],
	outfile: 'out/extension.js',
	sourcemap: prod ? false : 'inline',
	minify: prod,
	treeShaking: true,
	logLevel: 'info',
};

/**
 * 프리뷰 웹뷰(브라우저)에서 도는 스크립트.
 * placeholder div를 @pug-frame/canvas로 렌더링한다. canvas·render를 함께 번들한다.
 */
const previewBuild = {
	banner: { js: banner },
	entryPoints: ['src/preview.ts'],
	bundle: true,
	platform: 'browser',
	format: 'iife',
	target: 'es2021',
	outfile: 'media/pug-frame-preview.js',
	sourcemap: prod ? false : 'inline',
	minify: prod,
	treeShaking: true,
	logLevel: 'info',
};

if (prod) {
	await esbuild.build(extensionBuild);
	await esbuild.build(previewBuild);
	process.exit(0);
} else {
	const extensionCtx = await esbuild.context(extensionBuild);
	const previewCtx = await esbuild.context(previewBuild);
	await Promise.all([extensionCtx.watch(), previewCtx.watch()]);
}
